version: "3.9"
services:
  database_mysql:
    image: mysql:8.0.17
    container_name: database_cms
    hostname: localhost
    ports:
      - 3304:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=cms
      - MYSQL_USER=cms
      - MYSQL_PASSWORD=cms
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - ./.docker/database_cms:/var/lib/mysql