spring:
  graphql:
    graphiql:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3304/cms?useTimezone=true&serverTimezone=UTC
    username: cms
    password: cms
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      show-sql=: false